const rawWorks=[
['舊情雨MV','MV製作','mv','nbm-z7UgRxY','04:29','16:9','三立戲劇《百味人生》片頭曲 MV《舊情雨》,參與現場拍攝執行。','參與 MV 現場拍攝執行,協助掌鏡運鏡與現場素材整理,部分畫面透過 AI 生成技術製作,將原始無雨鏡頭轉換為下雨情境,補足現場無法呈現的畫面需求。後製調色投入大量心力反覆調整,力求 AI 生成畫面與實拍素材的色調、質感無縫銜接,最終使用 DaVinci Resolve 完成全片調色,呈現統一且具戲劇張力的視覺效果。'],
['拳擊社群形象廣告','品牌廣告','brand','XwXZWwbuKZ0','00:48','9:16','拳擊社群品牌廣告,傳遞拳擊館輕鬆自在且充滿歡笑的運動氛圍。影片呈現學員在專業師資引導下扎實學習技巧、享受拳擊樂趣,並結合周邊合作店面的美食體驗,展現豐富的社群生活。','負責現場紀錄(側拍)、後製剪輯與調色。以快節奏卡點展現拳擊動作的爆發力與學員投入的感染力,調色上拉高對比度、打造黑金視覺質感,強調動作線條與空間力量感,並搭配動態字幕強化品牌識別。使用 CapCut 剪輯、DaVinci Resolve 調色。'],
['食品行銷影片','商品影片','product','IdSZfzOoKYo','00:32','9:16','產品開箱類型短片,聚焦整支蝦乾製零食的原型與質地,以近景鏡頭搭配慢動作呈現,在 30 秒內完整呈現產品賣點。','負責蝦乾零食開箱短片之企劃發想與拍攝製作規劃,聚焦整支蝦體紋理光澤與酥脆口感之感官呈現,透過近景微距鏡頭與特寫快剪,在 30 秒內完整傳遞產品賣點,並延伸規劃完整拍攝執行方案。'],
['頭皮養護形象片','品牌廣告','brand','No-u4KVxtUc','00:52','9:16','透過朦朧霧氣與柔和光線,營造出靜謐放鬆的空間氛圍,帶領觀眾沉浸在頭皮養護的療癒時刻。','從腳本構思到完稿剪輯,採一條龍製作流程。調色以霧面質感詮釋朦朧氛圍,強化空間的沉靜感,搭配柔和轉場與慢節奏敘事,呈現放鬆舒緩的視覺體驗。'],
['頭皮養護外泌體產品行銷','商品影片','product','azpw234W-_Y','00:53','9:16','以情境劇形式呈現產品使用歷程,切入髮量稀疏、掉髮困擾等真實痛點,透過故事化敘事展現產品價值。','一條龍製作,從腳本構思、情境劇拍攝到後製完稿全程負責,確保產品功效與故事情節緊密扣合。'],
['海產形象廣告','品牌廣告','brand','4YunCKEDEN0','00:34','9:16','以下班後的日常場景切入,捕捉女主角卸下一身疲憊、窩在沙發角落的片刻,傳遞「累的時候,就想吃點好的」這份貼近生活的情感共鳴。','雙方共同討論腳本並確認拍攝方向與情境細節,定案後進行現場實拍,後續進行剪輯與調色,以暗色低對比營造居家夜晚的靜謐感。'],
['日本神社巡禮','生活vlog','vlog','MhMwWkb1_I8','00:39','9:16','尾山神社','個人生活 vlog,記錄尾山神社巡禮過程,以自然的剪輯步調保留旅行的真實節奏感,搭配環境音與音樂增添氛圍感。'],
['日本探店','生活vlog','vlog','qXfahkGYg2Y','00:41','9:16','魚介人','探店類 vlog,記錄「魚介人」用餐體驗,剪輯著重畫面氛圍與美食呈現,搭配字幕點出重點資訊。'],
['咖啡廳探店','生活vlog','vlog','bGoxSi9lKyw','00:35','9:16','神諭咖啡','以光影交錯的畫面語言,捕捉杯中氣泡緩緩浮動、酒紅色高腳杯映著暖光的細膩瞬間,帶領觀眾走進一場如夢似幻的午後探店時光。'],
['日本扭蛋篇','生活vlog','vlog','EJSmuKjFaug','00:36','9:16','生活趣味短片,記錄日本轉蛋店家探索過程。','生活趣味短片,記錄日本轉蛋店家探索過程,輕鬆節奏快,搭配趣味字幕增加觀看樂趣。']
];
const works=rawWorks.map(([title,category,key,yt,duration,ratio,summary,notes],id)=>({title,category,key,yt,duration,ratio,summary,notes,id}));
const categories=[['all','全部'],['brand','品牌廣告'],['product','產品影片'],['vlog','生活vlog'],['mv','MV製作']];let filter='all',selected=0,playing=false;
const $=s=>document.querySelector(s),thumb=id=>`https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
function activeWorks(){return filter==='all'?works:works.filter(w=>w.key===filter)}
function render(){let list=activeWorks();if(!list.some(w=>w.id===selected)){selected=list[0].id;playing=false}const w=works[selected];$('#filters').innerHTML=categories.map(([key,label])=>`<button class="filter ${key===filter?'active':''}" data-filter="${key}">${label}</button>`).join('');$('#stage').className=`stage ${w.ratio==='16:9'?'landscape':'portrait'}`;$('#stage').innerHTML=playing?`<iframe src="https://www.youtube.com/embed/${w.yt}?rel=0&autoplay=0&controls=1&playsinline=1&fs=1" title="${w.title}" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>`:`<img src="${thumb(w.yt)}" alt="${w.title}" /><span class="stage-meta">${w.category} · ${w.duration} · ${w.ratio}</span><button class="play" aria-label="播放 ${w.title}">▷</button>`;$('#thumbnailGrid').innerHTML=list.map(x=>`<button class="thumbnail ${x.id===selected?'selected':''}" data-id="${x.id}" aria-label="選擇 ${x.title}"><img src="${thumb(x.yt)}" alt="" /><span>${x.title}</span></button>`).join('');$('#details').innerHTML=`<div class="tags"><span class="tag">${w.category}</span><span class="tag">${w.ratio}</span><span class="tag">${w.duration}</span></div><h2>${w.title}</h2><p>${w.summary}</p><div class="label">製作說明</div><p class="notes">${w.notes}</p>`;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.id);playing=false;render()});$('.play')?.addEventListener('click',()=>{playing=true;render()})}
function enableVideo(video){const play=()=>video.play().catch(()=>{});video.muted=true;video.loop=true;play();video.addEventListener('loadeddata',play)}enableVideo($('#backgroundVideo'));const hero=$('#heroVideo');enableVideo(hero);hero.addEventListener('timeupdate',()=>$('#heroProgress').style.width=`${hero.duration?hero.currentTime/hero.duration*100:0}%`);$('#skipBack').onclick=()=>hero.currentTime=Math.max(0,hero.currentTime-10);$('#skipForward').onclick=()=>hero.currentTime=Math.min(hero.duration||0,hero.currentTime+10);$('#muteToggle').onclick=()=>{hero.muted=!hero.muted;$('#soundIcon').textContent=hero.muted?'▶':'Ⅱ';$('#muteToggle').setAttribute('aria-label',hero.muted?'開啟聲音':'靜音')};render();
document.addEventListener('click',event=>{const thumbnail=event.target.closest('[data-id]');if(!thumbnail)return;event.preventDefault();event.stopImmediatePropagation();selected=Number(thumbnail.dataset.id);playing=true;render()},true);
new MutationObserver(()=>{const frame=$('#stage iframe');const actions=$('#playerActions');if(!frame){actions.hidden=true;return}const work=works[selected];actions.hidden=false;actions.innerHTML=`<button type="button" data-expand-viewer="true">放大觀看</button><a href="https://www.youtube.com/watch?v=${work.yt}" target="_blank" rel="noopener">在 YouTube 觀看</a>`}).observe($('#stage'),{childList:true});
document.addEventListener('click',event=>{const expand=event.target.closest('[data-expand-viewer]');const close=event.target.closest('.viewer-close');const modal=$('#viewerModal');if(expand){const work=works[selected];$('#viewerFrame').innerHTML=`<iframe src="https://www.youtube.com/embed/${work.yt}?rel=0&autoplay=0&controls=1&playsinline=1&fs=1" title="${work.title}" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>`;modal.hidden=false}if(close||event.target===modal){modal.hidden=true;$('#viewerFrame').innerHTML=''}});
